language: php

sudo: false

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 5.6
        - php: 7.0
          env: TWIG="1.*"
        - php: 7.0
          env: TWIG="2.*"
        - php: 7.1
          env: TWIG="1.*"
        - php: 7.1
          env: TWIG="2.*"
        - php: 7.2
          env: TWIG="1.*"
        - php: 7.2
          env: TWIG="2.*"

before_install:
  - if [ "$TWIG" != "" ]; then composer require --dev --no-update twig/twig=$TWIG; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist

script: phpunit
